/// <reference types="node" />
import { EventEmitter } from 'events';
import { Logger } from './Logger';
import { LogSeverity } from './LogSeverity';
import { TokenManager } from './TokenManager';
import { Database } from './Database';
import { IHandler } from './IHandler';
import { Config } from './Config';
export declare abstract class Application extends EventEmitter {
    private logger;
    private name;
    private configPath;
    private config;
    private tokenManager;
    private server;
    private db;
    private _logConfigDefaulting;
    private _argv;
    constructor(name: string, configPath: string, logSeverity?: LogSeverity);
    private $buildArgOptions;
    protected _buildArgOptions(args: any): void;
    getRequestSizeLimit(): number;
    attachHandler(path: string, HandlerClass: IHandler): void;
    protected abstract attachHandlers(): Promise<void>;
    loadConfig(path: string): Promise<any>;
    getName(): string;
    getLogger(): Logger;
    getConfig(): Config;
    protected onConfigLoad(config: Config): void;
    setTokenManager(tokenManager: TokenManager): void;
    getTokenManager(): TokenManager;
    getDB(): Database;
    getCmdLineArgs(): any;
    protected initDB(config: Config): Promise<Database>;
    protected _createLogger(): Logger;
    protected _setDefaultLogLevel(): void;
    protected _parseLogLevelConfig(config: Config): LogSeverity;
    private _llStrToSeverity;
    protected onReady(): void;
}
